require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvestigationTypesController do

  # This should return the minimal set of attributes required to create a valid
  # InvestigationType. As you add validations to InvestigationType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "investigation_type" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InvestigationTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all investigation_types as @investigation_types" do
      investigation_type = InvestigationType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:investigation_types).should eq([investigation_type])
    end
  end

  describe "GET show" do
    it "assigns the requested investigation_type as @investigation_type" do
      investigation_type = InvestigationType.create! valid_attributes
      get :show, {:id => investigation_type.to_param}, valid_session
      assigns(:investigation_type).should eq(investigation_type)
    end
  end

  describe "GET new" do
    it "assigns a new investigation_type as @investigation_type" do
      get :new, {}, valid_session
      assigns(:investigation_type).should be_a_new(InvestigationType)
    end
  end

  describe "GET edit" do
    it "assigns the requested investigation_type as @investigation_type" do
      investigation_type = InvestigationType.create! valid_attributes
      get :edit, {:id => investigation_type.to_param}, valid_session
      assigns(:investigation_type).should eq(investigation_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InvestigationType" do
        expect {
          post :create, {:investigation_type => valid_attributes}, valid_session
        }.to change(InvestigationType, :count).by(1)
      end

      it "assigns a newly created investigation_type as @investigation_type" do
        post :create, {:investigation_type => valid_attributes}, valid_session
        assigns(:investigation_type).should be_a(InvestigationType)
        assigns(:investigation_type).should be_persisted
      end

      it "redirects to the created investigation_type" do
        post :create, {:investigation_type => valid_attributes}, valid_session
        response.should redirect_to(InvestigationType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved investigation_type as @investigation_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvestigationType.any_instance.stub(:save).and_return(false)
        post :create, {:investigation_type => { "investigation_type" => "invalid value" }}, valid_session
        assigns(:investigation_type).should be_a_new(InvestigationType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvestigationType.any_instance.stub(:save).and_return(false)
        post :create, {:investigation_type => { "investigation_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested investigation_type" do
        investigation_type = InvestigationType.create! valid_attributes
        # Assuming there are no other investigation_types in the database, this
        # specifies that the InvestigationType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InvestigationType.any_instance.should_receive(:update_attributes).with({ "investigation_type" => "MyString" })
        put :update, {:id => investigation_type.to_param, :investigation_type => { "investigation_type" => "MyString" }}, valid_session
      end

      it "assigns the requested investigation_type as @investigation_type" do
        investigation_type = InvestigationType.create! valid_attributes
        put :update, {:id => investigation_type.to_param, :investigation_type => valid_attributes}, valid_session
        assigns(:investigation_type).should eq(investigation_type)
      end

      it "redirects to the investigation_type" do
        investigation_type = InvestigationType.create! valid_attributes
        put :update, {:id => investigation_type.to_param, :investigation_type => valid_attributes}, valid_session
        response.should redirect_to(investigation_type)
      end
    end

    describe "with invalid params" do
      it "assigns the investigation_type as @investigation_type" do
        investigation_type = InvestigationType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvestigationType.any_instance.stub(:save).and_return(false)
        put :update, {:id => investigation_type.to_param, :investigation_type => { "investigation_type" => "invalid value" }}, valid_session
        assigns(:investigation_type).should eq(investigation_type)
      end

      it "re-renders the 'edit' template" do
        investigation_type = InvestigationType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvestigationType.any_instance.stub(:save).and_return(false)
        put :update, {:id => investigation_type.to_param, :investigation_type => { "investigation_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested investigation_type" do
      investigation_type = InvestigationType.create! valid_attributes
      expect {
        delete :destroy, {:id => investigation_type.to_param}, valid_session
      }.to change(InvestigationType, :count).by(-1)
    end

    it "redirects to the investigation_types list" do
      investigation_type = InvestigationType.create! valid_attributes
      delete :destroy, {:id => investigation_type.to_param}, valid_session
      response.should redirect_to(investigation_types_url)
    end
  end

end
