require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StakeholderCompanyTypesController do

  # This should return the minimal set of attributes required to create a valid
  # StakeholderCompanyType. As you add validations to StakeholderCompanyType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "takeholder_company_type" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StakeholderCompanyTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stakeholder_company_types as @stakeholder_company_types" do
      stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stakeholder_company_types).should eq([stakeholder_company_type])
    end
  end

  describe "GET show" do
    it "assigns the requested stakeholder_company_type as @stakeholder_company_type" do
      stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
      get :show, {:id => stakeholder_company_type.to_param}, valid_session
      assigns(:stakeholder_company_type).should eq(stakeholder_company_type)
    end
  end

  describe "GET new" do
    it "assigns a new stakeholder_company_type as @stakeholder_company_type" do
      get :new, {}, valid_session
      assigns(:stakeholder_company_type).should be_a_new(StakeholderCompanyType)
    end
  end

  describe "GET edit" do
    it "assigns the requested stakeholder_company_type as @stakeholder_company_type" do
      stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
      get :edit, {:id => stakeholder_company_type.to_param}, valid_session
      assigns(:stakeholder_company_type).should eq(stakeholder_company_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StakeholderCompanyType" do
        expect {
          post :create, {:stakeholder_company_type => valid_attributes}, valid_session
        }.to change(StakeholderCompanyType, :count).by(1)
      end

      it "assigns a newly created stakeholder_company_type as @stakeholder_company_type" do
        post :create, {:stakeholder_company_type => valid_attributes}, valid_session
        assigns(:stakeholder_company_type).should be_a(StakeholderCompanyType)
        assigns(:stakeholder_company_type).should be_persisted
      end

      it "redirects to the created stakeholder_company_type" do
        post :create, {:stakeholder_company_type => valid_attributes}, valid_session
        response.should redirect_to(StakeholderCompanyType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stakeholder_company_type as @stakeholder_company_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        StakeholderCompanyType.any_instance.stub(:save).and_return(false)
        post :create, {:stakeholder_company_type => { "takeholder_company_type" => "invalid value" }}, valid_session
        assigns(:stakeholder_company_type).should be_a_new(StakeholderCompanyType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StakeholderCompanyType.any_instance.stub(:save).and_return(false)
        post :create, {:stakeholder_company_type => { "takeholder_company_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stakeholder_company_type" do
        stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
        # Assuming there are no other stakeholder_company_types in the database, this
        # specifies that the StakeholderCompanyType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StakeholderCompanyType.any_instance.should_receive(:update_attributes).with({ "takeholder_company_type" => "MyString" })
        put :update, {:id => stakeholder_company_type.to_param, :stakeholder_company_type => { "takeholder_company_type" => "MyString" }}, valid_session
      end

      it "assigns the requested stakeholder_company_type as @stakeholder_company_type" do
        stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
        put :update, {:id => stakeholder_company_type.to_param, :stakeholder_company_type => valid_attributes}, valid_session
        assigns(:stakeholder_company_type).should eq(stakeholder_company_type)
      end

      it "redirects to the stakeholder_company_type" do
        stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
        put :update, {:id => stakeholder_company_type.to_param, :stakeholder_company_type => valid_attributes}, valid_session
        response.should redirect_to(stakeholder_company_type)
      end
    end

    describe "with invalid params" do
      it "assigns the stakeholder_company_type as @stakeholder_company_type" do
        stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StakeholderCompanyType.any_instance.stub(:save).and_return(false)
        put :update, {:id => stakeholder_company_type.to_param, :stakeholder_company_type => { "takeholder_company_type" => "invalid value" }}, valid_session
        assigns(:stakeholder_company_type).should eq(stakeholder_company_type)
      end

      it "re-renders the 'edit' template" do
        stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StakeholderCompanyType.any_instance.stub(:save).and_return(false)
        put :update, {:id => stakeholder_company_type.to_param, :stakeholder_company_type => { "takeholder_company_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stakeholder_company_type" do
      stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
      expect {
        delete :destroy, {:id => stakeholder_company_type.to_param}, valid_session
      }.to change(StakeholderCompanyType, :count).by(-1)
    end

    it "redirects to the stakeholder_company_types list" do
      stakeholder_company_type = StakeholderCompanyType.create! valid_attributes
      delete :destroy, {:id => stakeholder_company_type.to_param}, valid_session
      response.should redirect_to(stakeholder_company_types_url)
    end
  end

end
