require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StructureTypesController do

  # This should return the minimal set of attributes required to create a valid
  # StructureType. As you add validations to StructureType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "structure_type" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StructureTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all structure_types as @structure_types" do
      structure_type = StructureType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:structure_types).should eq([structure_type])
    end
  end

  describe "GET show" do
    it "assigns the requested structure_type as @structure_type" do
      structure_type = StructureType.create! valid_attributes
      get :show, {:id => structure_type.to_param}, valid_session
      assigns(:structure_type).should eq(structure_type)
    end
  end

  describe "GET new" do
    it "assigns a new structure_type as @structure_type" do
      get :new, {}, valid_session
      assigns(:structure_type).should be_a_new(StructureType)
    end
  end

  describe "GET edit" do
    it "assigns the requested structure_type as @structure_type" do
      structure_type = StructureType.create! valid_attributes
      get :edit, {:id => structure_type.to_param}, valid_session
      assigns(:structure_type).should eq(structure_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StructureType" do
        expect {
          post :create, {:structure_type => valid_attributes}, valid_session
        }.to change(StructureType, :count).by(1)
      end

      it "assigns a newly created structure_type as @structure_type" do
        post :create, {:structure_type => valid_attributes}, valid_session
        assigns(:structure_type).should be_a(StructureType)
        assigns(:structure_type).should be_persisted
      end

      it "redirects to the created structure_type" do
        post :create, {:structure_type => valid_attributes}, valid_session
        response.should redirect_to(StructureType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved structure_type as @structure_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        StructureType.any_instance.stub(:save).and_return(false)
        post :create, {:structure_type => { "structure_type" => "invalid value" }}, valid_session
        assigns(:structure_type).should be_a_new(StructureType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StructureType.any_instance.stub(:save).and_return(false)
        post :create, {:structure_type => { "structure_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested structure_type" do
        structure_type = StructureType.create! valid_attributes
        # Assuming there are no other structure_types in the database, this
        # specifies that the StructureType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StructureType.any_instance.should_receive(:update_attributes).with({ "structure_type" => "MyString" })
        put :update, {:id => structure_type.to_param, :structure_type => { "structure_type" => "MyString" }}, valid_session
      end

      it "assigns the requested structure_type as @structure_type" do
        structure_type = StructureType.create! valid_attributes
        put :update, {:id => structure_type.to_param, :structure_type => valid_attributes}, valid_session
        assigns(:structure_type).should eq(structure_type)
      end

      it "redirects to the structure_type" do
        structure_type = StructureType.create! valid_attributes
        put :update, {:id => structure_type.to_param, :structure_type => valid_attributes}, valid_session
        response.should redirect_to(structure_type)
      end
    end

    describe "with invalid params" do
      it "assigns the structure_type as @structure_type" do
        structure_type = StructureType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StructureType.any_instance.stub(:save).and_return(false)
        put :update, {:id => structure_type.to_param, :structure_type => { "structure_type" => "invalid value" }}, valid_session
        assigns(:structure_type).should eq(structure_type)
      end

      it "re-renders the 'edit' template" do
        structure_type = StructureType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StructureType.any_instance.stub(:save).and_return(false)
        put :update, {:id => structure_type.to_param, :structure_type => { "structure_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested structure_type" do
      structure_type = StructureType.create! valid_attributes
      expect {
        delete :destroy, {:id => structure_type.to_param}, valid_session
      }.to change(StructureType, :count).by(-1)
    end

    it "redirects to the structure_types list" do
      structure_type = StructureType.create! valid_attributes
      delete :destroy, {:id => structure_type.to_param}, valid_session
      response.should redirect_to(structure_types_url)
    end
  end

end
